version: "3.8"

services:
  backend:
    build: .
    container_name: tiamat-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  db:
    image: mysql:8.0
    container_name: tiamat-mysql
    ports:
      - "3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
